---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
      - ["forwarded_port", {guest: 80, host: 8888}]
      customize:
        cpus: 2
        memory: 3024
        cpuexecutioncap: 100

suites:
  - name: default
    run_list:
      - recipe[midokura]
    attributes: { midokura: { 'repo-username': 'USERNAME', 'repo-password': 'PASSWORD' }}
